
version: "3.7"
services:
  mongo:
    image: mongo:4.0.10
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - db

  backend:
    build:
      context: backend
    networks:
      - kepler
      - db
    ports:
      - 8103:8103
    depends_on:
      - mongo

  frontend:
    build:
      context: frontend
    ports:
      - 3000:3000
    networks:
      - kepler
    depends_on:
      - backend

networks:
  db:
    driver: bridge
  kepler:
    driver: bridge
volumes:
  mongodb_data_container: