server:
  port: 8103
  undertow:
    worker-threads: 60

logging:
  pattern:
    console: "[%d] : %-5level : %msg%n"

management:
  endpoint:
    health:
      show-details: "ALWAYS"
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

database:
  mongo:
    address: mongo
    port: 27017

auth:
  jwt:
    key: "0e891b9a-ab85-482c-a376-6ef3454c230d"
    validity: 900000